config/routes.rb
# frozen_string_literal: true

Spree::Core::Engine.routes.draw do
  root to: 'home#index'

  namespace :admin do
    root to: 'root#index'
  end

  devise_for(:spree_user, {
               class_name: 'Spree::User',
               controllers: {
                 sessions: 'spree/user_sessions',
                 registrations: 'spree/user_registrations',
                 passwords: 'spree/user_passwords',
                 confirmations: 'spree/user_confirmations'
               },
               skip: %i[unlocks omniauth_callbacks],
               path_names: { sign_out: 'logout' },
               path_prefix: :user,
               router_name: :spree
             })

  # resources :users, only: %i[edit update]

  # devise_scope :spree_user do
  #   get '/login', to: 'user_sessions#new', as: :login
  #   post '/login', to: 'user_sessions#create', as: :create_new_session
  #   match '/logout', to: 'user_sessions#destroy', as: :logout, via: Devise.sign_out_via
  #   get '/signup', to: 'user_registrations#new', as: :signup
  #   post '/signup', to: 'user_registrations#create', as: :registration
  #   get '/password/recover', to: 'user_passwords#new', as: :recover_password
  #   post '/password/recover', to: 'user_passwords#create', as: :reset_password
  #   get '/password/change', to: 'user_passwords#edit', as: :edit_password
  #   put '/password/change', to: 'user_passwords#update', as: :update_password
  #   get '/confirm', to: 'user_confirmations#show', as: :confirmation if Spree::Auth::Config[:confirmable]
  # end

  resource :account, controller: 'users'

  resources :products, only: %i[index show]

  get '/locale/set', to: 'locale#set'
  post '/locale/set', to: 'locale#set', as: :select_locale

  # non-restful checkout stuff
  get '/checkout/registration', to: 'checkout#registration', as: :checkout_registration
  put '/checkout/registration', to: 'checkout#update_registration', as: :update_checkout_registration
  patch '/checkout/update/:state', to: 'checkout#update', as: :update_checkout
  get '/checkout/:state', to: 'checkout#edit', as: :checkout_state
  get '/checkout', to: 'checkout#edit', as: :checkout

  get '/orders/populate', to: 'orders#populate_redirect'
  get '/orders/:id/token/:token' => 'orders#show', as: :token_order

  resources :orders, except: %i[index new create destroy] do
    post :populate, on: :collection
    resources :coupon_codes, only: :create
  end

  get '/cart', to: 'orders#edit', as: :cart
  patch '/cart', to: 'orders#update', as: :update_cart
  put '/cart/empty', to: 'orders#empty', as: :empty_cart

  # route globbing for pretty nested taxon and product paths
  get '/t/*id', to: 'taxons#show', as: :nested_taxons

  get '/unauthorized', to: 'home#unauthorized', as: :unauthorized
  get '/cart_link', to: 'store#cart_link', as: :cart_link
end
Rails.application.routes.draw do
  # root to: redirect('/admin')
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/spree/admin/promotions/_actions.html.erb
<fieldset id="action_fields" class="no-border-top">

  <%= form_tag spree.admin_promotion_promotion_actions_path(@promotion), remote: true, id: 'new_promotion_action_form' do %>
    <% options = options_for_select(  Rails.application.config.spree.promotions.actions.map {|action| [ action.model_name.human, action.name] } ) %>
    <fieldset>
      <legend align="center"><%= t('spree.promotion_actions') %></legend>
      <% if can?(:update, @promotion) %>
        <div class="field">
          <%= label_tag :action_type, t('spree.adjustment_type')%>
          <%= admin_hint t('spree.adjustment_type'), t(:promotions, scope: [:spree, :hints, "spree/calculator"]) %>
          <%= select_tag 'action_type', options, include_blank: t(:choose_promotion_action, scope: 'spree'), class: 'custom-select fullwidth', required: true %>
        </div>
        <div class="filter-actions actions">
          <%= button_tag t('spree.actions.add'), class: 'btn btn-primary' %>
        </div>
      <% end %>
    </fieldset>
  <% end %>

  <%= form_for @promotion, url: spree.admin_promotion_path(@promotion), method: :put do |f| %>
    <div id="actions" class="filter_list">
      <% if @promotion.actions.any? %>
        <%= render partial: 'promotion_action',  collection: @promotion.actions %>
      <% else %>
        <div class="no-objects-found">
          <%= t('spree.no_actions_added') %>
        </div>
      <% end %>
    </div>
    <% if can?(:update, @promotion) %>
      <div class="filter-actions actions promotion-update">
        <%= button_tag t('spree.actions.update'), class: 'btn btn-primary' %>
      </div>
    <% end %>
  <% end %>

</fieldset>

app/views/spree/admin/promotions/_activations_edit.html.erb
<% if @promotion.apply_automatically? %>
  <p>
    <%= t('.auto') %>
  </p>
<% end %>

<% if @promotion.codes.count == 1 %>
  <p>
    <%= t('.single_code_html', code: @promotion.codes.first.value) %>
  </p>
<% elsif @promotion.codes.count > 1 %>
  <p>
    <%= t('.multiple_codes_html', count: @promotion.codes.count) %>
  </p>
<% end %>

<% if @promotion.path %>
  <div class="field">
    <%= f.label :path %>
    <%= f.text_field :path, class: "fullwidth" %>
  </div>
<% end %>

app/views/spree/admin/promotions/_activations_new.html.erb
<% activation_type = params[:activation_type] || 'single_code' %>
<div class="row" id="js_promotion_activation">
  <div class="col-3">
    <div class="form-check">
      <label class="form-check-label">
        <%= radio_button_tag('activation_type', 'auto', activation_type == 'auto') %>
        <%= t('.auto') %> <%= f.field_hint :promo_code_will_be_disabled %>
      </label>
    </div>
    <div class="form-check">
      <label class="form-check-label">
        <%= radio_button_tag('activation_type', 'single_code', activation_type == 'single_code') %>
        <%= t('.single_code') %>
      </label>
    </div>
    <div class="form-check">
      <label class="form-check-label">
        <%= radio_button_tag('activation_type', 'multiple_codes', activation_type == 'multiple_codes') %>
        <%= t('.multiple_codes') %>
      </label>
    </div>
  </div>
  <div class="col-9">
    <input name="promotion[apply_automatically]" type="hidden" value="0">
    <div data-activation-type="auto">
      <input name="promotion[apply_automatically]" type="hidden" value="1">
    </div>

    <div data-activation-type="single_code">
      <div class="field">
        <%= label_tag :single_code, Spree::PromotionCode.model_name.human, class: "required" %>
        <%= text_field_tag :single_code, @promotion.codes.first.try!(:value), class: "fullwidth", required: true %>
      </div>
    </div>

    <div data-activation-type="multiple_codes">
      <%= fields_for :promotion_code_batch, @promotion_code_batch do |batch| %>
        <%= render partial: 'spree/admin/promotion_code_batches/form_fields', locals: {f: f, batch: batch, promotion_id: params[:promotion_id]} %>
      <% end %>
    </div>

  </div>
</div>

app/views/spree/admin/promotions/_form.html.erb
<%= render partial: 'spree/shared/error_messages', locals: { target: @promotion } %>
<fieldset class="form-group no-border-bottom no-border-top">
  <div class="row">
    <div id="general_fields" class="col-9">
      <div class="row">
        <div class="col-12">
          <%= f.field_container :name do %>
            <%= f.label :name, class: 'required' %>
            <%= f.text_field :name, class: 'fullwidth', required: true %>
          <% end %>

          <%= f.field_container :description do %>
            <%= f.label :description %><br />
            <%= f.text_area :description, rows: 7, class: 'fullwidth' %>
            <span class="info">
              <%= t('spree.character_limit') %>
            </span>
          <% end %>

          <%= f.field_container :category do %>
            <%= f.label :promotion_category_id, Spree::PromotionCategory.model_name.human %><br />
            <%= f.collection_select(:promotion_category_id, @promotion_categories, :id, :name, { include_blank: t('spree.match_choices.none') }, { class: 'custom-select fullwidth' }) %>
          <% end %>
        </div>
      </div>
    </div>

    <div id="expiry_fields" class="col-3">
      <%= f.field_container :overall_usage_limit do %>
        <%= f.label :usage_limit %><br />
        <%= f.number_field :usage_limit, min: 0, class: 'fullwidth' %><br>
        <span class="info">
          <%= t('spree.current_promotion_usage', count: @promotion.usage_count) %>
        </span>
      <% end %>

      <% if @promotion.persisted? %>
        <%= f.field_container :per_code_usage_limit do %>
          <%= f.label :per_code_usage_limit %><br />
          <%= f.number_field :per_code_usage_limit, min: 0, class: 'fullwidth' %><br>
        <% end %>
      <% end %>

      <div id="starts_at_field" class="field">
        <%= f.label :starts_at %>
        <%= f.field_hint :starts_at %>
        <%= f.text_field :starts_at, value: datepicker_field_value(@promotion.starts_at, with_time: true), placeholder: t(".starts_at_placeholder"), class: 'datepicker datepicker-from fullwidth', data: { :'enable-time' => true, :'default-hour' => 0 } %>
      </div>

      <div id="expires_at_field" class="field">
        <%= f.label :expires_at %>
        <%= f.field_hint :expires_at %>
        <%= f.text_field :expires_at, value: datepicker_field_value(@promotion.expires_at, with_time: true), placeholder: t(".expires_at_placeholder"), class: 'datepicker datepicker-to fullwidth', data: { :'enable-time' => true, :'default-hour' => 0 } %>
      </div>
    </div>
  </div>
</fieldset>

<fieldset class="form-group no-border-bottom">
  <legend><%= t '.activation' %></legend>

  <% if @promotion.new_record? %>
    <%= render 'spree/admin/promotions/activations_new', f: f %>
  <% else %>
    <%= render 'spree/admin/promotions/activations_edit', f: f %>
  <% end %>
</fieldset>

app/views/spree/admin/promotions/_promotion_action.html.erb
<div class="promotion_action promotion-block <%= promotion_action.model_name.element %>" id="<%= dom_id promotion_action %>">
  <h6 class="promotion-title"><%= promotion_action.class.human_attribute_name(:description) %></h6>
  <% if can?(:destroy, promotion_action) %>
    <%= link_to_with_icon 'trash', '', spree.admin_promotion_promotion_action_path(@promotion, promotion_action), remote: true, method: :delete, class: 'delete' %>
  <% end %>

  <% param_prefix = "promotion[promotion_actions_attributes][#{promotion_action.id}]" %>
  <%= hidden_field_tag "#{param_prefix}[id]", promotion_action.id %>

  <%= render partial: "spree/shared/error_messages", locals: { target: promotion_action } %>
  <%= render partial: promotion_action.to_partial_path,
             locals: { promotion_action: promotion_action, param_prefix: param_prefix } %>
</div>

app/views/spree/admin/promotions/_promotion_rule.html.erb
<div class="promotion_rule promotion-block col-12" id="<%= dom_id promotion_rule %>">
  <% type_name = promotion_rule.model_name.element %>
  <h6 class='promotion-title <%= 'no-text' if type_name.in? %w(user_logged_in first_order one_use_per_user) %>'><%= promotion_rule.class.human_attribute_name(:description) %></h6>
  <% if can?(:destroy, promotion_rule) %>
    <%= link_to_with_icon 'trash', '', spree.admin_promotion_promotion_rule_path(@promotion, promotion_rule), remote: true, method: :delete, class: 'delete' %>
  <% end %>

  <% param_prefix = "promotion[promotion_rules_attributes][#{promotion_rule.id}]" %>
  <%= hidden_field_tag "#{param_prefix}[id]", promotion_rule.id %>
  <%= render partial: "spree/shared/error_messages", locals: { target: promotion_rule } %>
  <%= render partial: promotion_rule.to_partial_path, locals: { promotion_rule: promotion_rule, param_prefix: param_prefix } %>
</div>

app/views/spree/admin/promotions/_rules.html.erb
<fieldset id="rule_fields" class ="no-border-bottom no-border-top">

  <%= form_tag spree.admin_promotion_promotion_rules_path(@promotion), remote: true, id: 'new_product_rule_form' do %>
    <fieldset>
      <legend align="center"><%= t('spree.rules') %></legend>

      <% if can?(:update, @promotion) %>
        <div class="field">
          <%= label_tag :promotion_rule_type, t('spree.discount_rules') %>
          <%= select_tag('promotion_rule[type]', options_for_promotion_rule_types(@promotion), include_blank: t(:choose_promotion_rule, scope: 'spree'), class: 'custom-select fullwidth', required: true) %>
        </div>
        <div class="filter-actions actions">
          <%= button_tag t('spree.actions.add'), class: 'btn btn-primary' %>
        </div>
      <% end %>
    </fieldset>
  <% end %>


    <%= form_for @promotion, url: object_url, method: :put do |f| %>
      <fieldset class="no-border-top">
        <div id="promotion-policy-select" class="align-center row">
          <% Spree::Promotion::MATCH_POLICIES.each do |policy| %>
            <div class="col-6">
              <label><%= f.radio_button :match_policy, policy %> <%= t "spree.promotion_form.match_policies.#{policy}" %></label>
            </div>
          <% end %>
        </div>

        <div id="rules" class="filter_list">
          <% if @promotion.rules.any? %>
            <div class="col-12">
              <div class="row">
                <%= render partial: 'promotion_rule', collection: @promotion.rules, locals: {} %>
              </div>
            </div>
          <% else %>
            <div class="no-objects-found">
              <%= t('spree.no_rules_added') %>
            </div>
          <% end %>
        </div>

        <% if can?(:update, @promotion) %>
          <div class="promotion-update filter-actions actions">
            <%= button_tag t('spree.actions.update'), class: 'btn btn-primary' %>
          </div>
        <% end %>
      </fieldset>
    <% end %>
</fieldset>

app/views/spree/admin/promotions/edit.html.erb
<% admin_layout "full-width" %>

<% admin_breadcrumb(link_to plural_resource_name(Spree::Promotion), spree.admin_promotions_path) %>
<% admin_breadcrumb(@promotion.name) %>

<% content_for :page_actions do %>
  <li>
    <% if can?(:show, Spree::PromotionCode) %>
      <%= link_to t('spree.view_promotion_codes_list'), admin_promotion_promotion_codes_path(promotion_id: @promotion.id), class: 'btn btn-primary' %>

      <%= link_to t('spree.download_promotion_codes_list'), admin_promotion_promotion_codes_path(promotion_id: @promotion.id, format: :csv), class: 'btn btn-primary' %>
    <% end %>

    <% if can?(:show, Spree::PromotionCodeBatch) %>
      <%= link_to plural_resource_name(Spree::PromotionCodeBatch), admin_promotion_promotion_code_batches_path(promotion_id: @promotion.id), class: 'btn btn-primary' %>
    <% end %>
  </li>
<% end %>

<%= form_for @promotion, url: object_url, method: :put do |f| %>
  <%= render partial: 'form', locals: { f: f } %>
  <% if can?(:update, @promotion) %>
    <%= render partial: 'spree/admin/shared/edit_resource_links' %>
  <% end %>
<% end %>

<div id="promotion-filters" class="row">
  <div id="rules_container" class="col-6">
    <%= render partial: 'rules' %>
  </div>

  <div id="actions_container" class="col-6">
    <%= render partial: 'actions' %>
  </div>
</div>

app/views/spree/admin/promotions/index.html.erb
<% admin_breadcrumb(plural_resource_name(Spree::Promotion)) %>

<% content_for :page_actions do %>
  <% if can? :create, Spree::Promotion %>
    <li>
      <%= link_to t('spree.new_promotion'), spree.new_admin_promotion_path, class: 'btn btn-primary' %>
    </li>
  <% end %>
<% end %>

<% content_for :table_filter_title do %>
  <%= t('spree.search') %>
<% end %>

<% content_for :table_filter do %>
  <div data-hook="admin_promotions_index_search">
    <%= search_form_for [:admin, @search] do |f| %>
      <div class="row">
        <div class="col-4">
          <div class="field">
            <%= label_tag :q_name_cont, Spree::Promotion.human_attribute_name(:name) %>
            <%= f.text_field :name_cont, tabindex: 1 %>
          </div>
        </div>

        <div class="col-2">
          <div class="field">
            <%= label_tag :q_codes_value_cont, Spree::Promotion.human_attribute_name(:code) %>
            <%= f.text_field :codes_value_cont, tabindex: 1 %>
          </div>
        </div>

        <div class="col-2">
          <div class="field">
            <%= label_tag :q_path_cont, Spree::Promotion.human_attribute_name(:path) %>
            <%= f.text_field :path_cont, tabindex: 1 %>
          </div>
        </div>

        <div class="col-2">
          <div class="field">
            <%= label_tag :q_promotion_category_id_eq, Spree::PromotionCategory.model_name.human %><br>
            <%= f.collection_select(:promotion_category_id_eq, @promotion_categories, :id, :name, { include_blank: t('spree.match_choices.all') }, { class: 'custom-select fullwidth' }) %>
          </div>
        </div>

        <div class="col-2">
          <div class="field">
            <%= label_tag :active, t('spree.active') %><br>
            <%= f.check_box :active, label: false, as: :boolean, checked_value: true %>
          </div>
        </div>
      </div>

      <div class="clearfix"></div>

      <div class="actions filter-actions">
        <div data-hook="admin_promotions_index_search_buttons">
          <%= button_tag t('spree.filter_results'), class: 'btn btn-primary' %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>


<%= paginate @promotions, theme: "solidus_admin" %>

<% if @promotions.length > 0 %>
  <table class="index">
    <thead>
      <tr>
        <th><%= Spree::Promotion.human_attribute_name(:name) %></th>
        <th><%= Spree::Promotion.human_attribute_name(:code) %></th>
        <th><%= Spree::Promotion.human_attribute_name(:status) %></th>
        <th><%= Spree::Promotion.human_attribute_name(:usage_limit) %></th>
        <th><%= Spree::Promotion.human_attribute_name(:uses) %></th>
        <th><%= Spree::Promotion.human_attribute_name(:starts_at) %></th>
        <th><%= Spree::Promotion.human_attribute_name(:expires_at) %></th>
        <th class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @promotions.each do |promotion| %>
        <tr id="<%= spree_dom_id promotion %>">
          <td><%= promotion.name %></td>
          <td>
            <%= (promotion.codes.size == 1) ? promotion.codes.pluck(:value).first : t('spree.number_of_codes', count: promotion.codes.size) %>
          </td>
          <td>
            <span class="pill pill-<%= promotion.active? ? 'active' : 'inactive' %>">
              <%= t(admin_promotion_status(promotion), scope: 'spree.admin.promotion_status') %>
            </span>
          </td>
          <td>
            <%= promotion.usage_limit.nil? ? "∞" : promotion.usage_limit %>
          </td>
          <td>
            <%= promotion.usage_count %>
          </td>
          <td>
            <%= promotion.starts_at.to_s(:long) if promotion.starts_at %>
          </td>
          <td>
            <%= promotion.expires_at.to_s(:long) if promotion.expires_at %>
          </td>
          <td class="actions">
            <% if can?(:edit, promotion) %>
              <%= link_to_edit promotion, no_text: true %>
            <% end %>
            <% if can?(:destroy, promotion) %>
              <%= link_to_delete promotion, no_text: true %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="no-objects-found">
    <%= render 'spree/admin/shared/no_objects_found',
                 resource: Spree::Promotion,
                 new_resource_url: new_object_url %>
  </div>
<% end %>

app/views/spree/admin/promotions/new.html.erb
<% admin_layout "full-width" %>

<% admin_breadcrumb(link_to plural_resource_name(Spree::Promotion), spree.admin_promotions_path) %>
<% admin_breadcrumb(t('spree.new_promotion')) %>

<%= form_for @promotion, url: collection_url do |f| %>
  <%= render partial: 'form', locals: { f: f } %>
  <%= render partial: 'spree/admin/shared/new_resource_links' %>
<% end %>