config/routes.rb
# frozen_string_literal: true

Spree::Core::Engine.routes.draw do
  root to: 'home#index'

  namespace :admin do
    root to: 'root#index'
  end

  devise_for(:spree_user, {
               class_name: 'Spree::User',
               controllers: {
                 sessions: 'spree/user_sessions',
                 registrations: 'spree/user_registrations',
                 passwords: 'spree/user_passwords',
                 confirmations: 'spree/user_confirmations'
               },
               skip: %i[unlocks omniauth_callbacks],
               path_names: { sign_out: 'logout' },
               path_prefix: :user,
               router_name: :spree
             })

  # resources :users, only: %i[edit update]

  # devise_scope :spree_user do
  #   get '/login', to: 'user_sessions#new', as: :login
  #   post '/login', to: 'user_sessions#create', as: :create_new_session
  #   match '/logout', to: 'user_sessions#destroy', as: :logout, via: Devise.sign_out_via
  #   get '/signup', to: 'user_registrations#new', as: :signup
  #   post '/signup', to: 'user_registrations#create', as: :registration
  #   get '/password/recover', to: 'user_passwords#new', as: :recover_password
  #   post '/password/recover', to: 'user_passwords#create', as: :reset_password
  #   get '/password/change', to: 'user_passwords#edit', as: :edit_password
  #   put '/password/change', to: 'user_passwords#update', as: :update_password
  #   get '/confirm', to: 'user_confirmations#show', as: :confirmation if Spree::Auth::Config[:confirmable]
  # end

  resource :account, controller: 'users'

  resources :products, only: %i[index show]

  get '/locale/set', to: 'locale#set'
  post '/locale/set', to: 'locale#set', as: :select_locale

  # non-restful checkout stuff
  get '/checkout/registration', to: 'checkout#registration', as: :checkout_registration
  put '/checkout/registration', to: 'checkout#update_registration', as: :update_checkout_registration
  patch '/checkout/update/:state', to: 'checkout#update', as: :update_checkout
  get '/checkout/:state', to: 'checkout#edit', as: :checkout_state
  get '/checkout', to: 'checkout#edit', as: :checkout

  get '/orders/populate', to: 'orders#populate_redirect'
  get '/orders/:id/token/:token' => 'orders#show', as: :token_order

  resources :orders, except: %i[index new create destroy] do
    post :populate, on: :collection
    resources :coupon_codes, only: :create
  end

  get '/cart', to: 'orders#edit', as: :cart
  patch '/cart', to: 'orders#update', as: :update_cart
  put '/cart/empty', to: 'orders#empty', as: :empty_cart

  # route globbing for pretty nested taxon and product paths
  get '/t/*id', to: 'taxons#show', as: :nested_taxons

  get '/unauthorized', to: 'home#unauthorized', as: :unauthorized
  get '/cart_link', to: 'store#cart_link', as: :cart_link
end
Rails.application.routes.draw do
  # root to: redirect('/admin')
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/spree/orders_controller.rb
# frozen_string_literal: true

module Spree
  class OrdersController < Spree::StoreController
    helper 'spree/products', 'spree/orders'

    respond_to :html

    before_action :store_guest_token
    before_action :assign_order, only: :update
    # note: do not lock the #edit action because that's where we redirect when we fail to acquire a lock
    around_action :lock_order, only: :update

    def show
      @order = Spree::Order.find_by!(number: params[:id])
      authorize! :show, @order, cookies.signed[:guest_token]
    end

    def update
      authorize! :update, @order, cookies.signed[:guest_token]
      if @order.contents.update_cart(order_params)
        @order.next if params.key?(:checkout) && @order.cart?

        respond_with(@order) do |format|
          format.html do
            if params.key?(:checkout)
              redirect_to checkout_state_path(@order.checkout_steps.first)
            else
              redirect_to cart_path
            end
          end
        end
      else
        respond_with(@order)
      end
    end

    # Shows the current incomplete order from the session
    def edit
      @order = current_order(build_order_if_necessary: true)
      authorize! :edit, @order, cookies.signed[:guest_token]
      associate_user
      if params[:id] && @order.number != params[:id]
        flash[:error] = t('spree.cannot_edit_orders')
        redirect_to cart_path
      end
    end

    # Adds a new item to the order (creating a new order if none already exists)
    def populate
      @order = current_order(create_order_if_necessary: true)
      authorize! :update, @order, cookies.signed[:guest_token]

      variant  = Spree::Variant.find(params[:variant_id])
      quantity = params[:quantity].present? ? params[:quantity].to_i : 1

      # 2,147,483,647 is crazy. See issue https://github.com/spree/spree/issues/2695.
      if !quantity.between?(1, 2_147_483_647)
        @order.errors.add(:base, t('spree.please_enter_reasonable_quantity'))
      else
        begin
          @line_item = @order.contents.add(variant, quantity)
        rescue ActiveRecord::RecordInvalid => error
          @order.errors.add(:base, error.record.errors.full_messages.join(", "))
        end
      end

      respond_with(@order) do |format|
        format.html do
          if @order.errors.any?
            flash[:error] = @order.errors.full_messages.join(", ")
            redirect_back_or_default(spree.root_path)
            return
          else
            redirect_to cart_path
          end
        end
      end
    end

    def populate_redirect
      flash[:error] = t('spree.populate_get_error')
      redirect_to spree.cart_path
    end

    def empty
      if @order = current_order
        authorize! :update, @order, cookies.signed[:guest_token]
        @order.empty!
      end

      redirect_to spree.cart_path
    end

    def accurate_title
      if @order && @order.completed?
        t('spree.order_number', number: @order.number)
      else
        t('spree.shopping_cart')
      end
    end

    private

    def store_guest_token
      cookies.permanent.signed[:guest_token] = params[:token] if params[:token]
    end

    def order_params
      if params[:order]
        params[:order].permit(*permitted_order_attributes)
      else
        {}
      end
    end

    def assign_order
      @order = current_order
      unless @order
        flash[:error] = t('spree.order_not_found')
        redirect_to(root_path) && return
      end
    end
  end
end

app/helpers/spree/orders_helper.rb
# frozen_string_literal: true

require 'truncate_html'
require 'app/helpers/truncate_html_helper'

module Spree
  module OrdersHelper
    include TruncateHtmlHelper

    def truncated_product_description(product)
      truncate_html(raw(product.description))
    end

    def order_just_completed?(order)
      flash[:order_completed] && order.present?
    end
  end
end

app/views/spree/admin/orders/_adjustments.html.erb
<fieldset class="no-border-bottom">
  <legend><%= title %></legend>
  <table>
    <thead>
      <tr>
        <th><%= Spree::Adjustment.human_attribute_name(:name)%></th>
        <th><%= Spree::Adjustment.human_attribute_name(:amount)%></th>
      </tr>
    </thead>
    <tbody data-hook="order_details_adjustments">
      <% adjustments.eligible.group_by(&:label).each do |label, adjustments| %>
        <tr class="total">
          <td><%= label %>:</td>
          <td class="total"><span><%= Spree::Money.new(adjustments.sum(&:amount), currency: adjustments.first.order.try(:currency)) %></span></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</fieldset>

app/views/spree/admin/orders/_carton.html.erb
<div id="<%= dom_id(carton) %>" data-hook="admin_carton_form">
  <fieldset class="no-border-bottom">
    <legend align="center" class="stock-location" data-hook="stock-location">
      <span class="carton-number"><%= carton.number %></span>
      -
      <span class="carton-state"><%= t('spree.shipment_states.shipped') %></span>
      <span class="carton-exchange"><%= Spree::Exchange.model_name.human if carton.any_exchanges? %></span>
      <%= t('spree.package_from') %>
      <strong class="stock-location-name" data-hook="stock-location-name">'<%= carton.stock_location.name %>'</strong>
    </legend>
  </fieldset>

  <table class="stock-contents carton index" data-hook="stock-contents">
    <colgroup>
      <col style="width: 10%;" />
      <col style="width: 45%;" />
      <col style="width: 15%;" />
      <col style="width: 15%;" />
      <col style="width: 15%;" />
    </colgroup>

    <thead>
      <th colspan="2"><%= Spree::LineItem.human_attribute_name(:description) %></th>
      <th><%= Spree::LineItem.human_attribute_name(:price) %></th>
      <th><%= Spree::LineItem.human_attribute_name(:quantity) %></th>
      <th><%= Spree::LineItem.human_attribute_name(:total) %></th>
    </thead>

    <tbody data-hook="carton-details" data-shipment-number="<%= carton.number %>" data-order-number="<%= order.number %>">
      <%= render 'spree/admin/orders/carton_manifest', carton: carton, order: order %>

      <tr class="show-method total">
        <% if method = carton.shipping_method %>
          <td colspan="5">
            <strong><%= method.name %></strong>
          </td>
        <% else %>
          <td colspan='5'><%= t('spree.no_shipping_method_selected') %></td>
        <% end %>
      </tr>

      <% if order.special_instructions.present? %>
        <tr class='special_instructions'>
          <td colspan="5">
            <strong><%= Spree::Order.human_attribute_name(:special_instructions) %>:&nbsp;</strong><%= order.special_instructions %>
          </td>
        </tr>
      <% end %>

      <tr class="show-tracking total">
        <td colspan="5">
          <% if carton.tracking.present? %>
            <strong><%= Spree::Carton.human_attribute_name(:tracking) %>:</strong>
            <% if carton.tracking_url %>
              <%= link_to carton.tracking, carton.tracking_url, target: "_blank" %>
            <% else %>
              <%= carton.tracking %>
            <% end %>
          <% else %>
            <i><%= t('spree.no_tracking_present') %></i>
          <% end %>
        </td>
      </tr>

      <tr class='shipment-numbers'>
        <td colspan="5">
          <strong><%= t('spree.shipment_numbers') %>:&nbsp;</strong><%= carton.shipment_numbers.join(", ") %>
        </td>
      </tr>

      <tr class='ship-date'>
        <td colspan="5">
          <strong><%= t('spree.shipment_date') %>:&nbsp;</strong><%= carton.display_shipped_at %>
        </td>
      </tr>

      <% if carton.orders.size > 1 %>
        <tr class='order-numbers'>
          <td colspan="5">
            <strong><%= t('spree.carton_orders') %>:&nbsp;</strong>
            <% (carton.orders - [order]).each do |order| %>
              <%= link_to order.number, edit_admin_order_path(order) %>
            <% end %>
          </td>
        </tr>
      <% end %>

      <% if carton.external_number.present? %>
        <tr class="external-number">
          <td colspan="5">
            <strong><%= t('spree.carton_external_number') %>:&nbsp;</strong><%= carton.external_number %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/spree/admin/orders/_carton_manifest.html.erb
<% carton.manifest_for_order(order).each do |item| %>
  <tr class="stock-item" data-item-quantity="<%= item.quantity %>">
    <td class="item-image">
      <%= render 'spree/admin/shared/image',
        image: (item.variant.gallery.images.first || item.variant.product.gallery.images.first),
        size: :mini %>
    </td>
    <td class="item-name">
      <%= link_to item.variant.product.name, edit_admin_product_path(item.variant.product) %><br><%= "(" + variant_options(item.variant) + ")" unless item.variant.option_values.empty? %>
      <% if item.variant.sku.present? %>
        <strong><%= Spree::Variant.human_attribute_name(:sku) %>:</strong>
        <%= item.variant.sku %>
      <% end %>
    </td>
    <td class="item-price"><%= item.line_item.single_money.to_html %></td>
    <td class="item-qty-show">
        <% item.states.each do |state,count| %>
          <%= count %> x <%= t(state, scope: 'spree.inventory_states') %>
        <% end %>
    </td>
    <td class="item-total"><%= line_item_shipment_price(item.line_item, item.quantity) %></td>
  </tr>
<% end %>

app/views/spree/admin/orders/_form.html.erb
 <div data-hook="admin_order_form_fields">
  <% if @line_item.try(:errors).present? %>
    <%= render partial: 'spree/shared/error_messages', locals: { target: @line_item } %>
  <% end %>

  <%= render :partial => "spree/admin/orders/carton", collection: @order.cartons.order(:shipped_at), locals: { order: order } %>
  <%= render :partial => "spree/admin/orders/shipment", collection: @order.shipments.order(:created_at), locals: { order: order } %>

  <%= render "spree/admin/orders/order_details", { order: order } %>

  <%= javascript_tag do -%>
    var order_number = '<%= @order.number %>';
    var shipments = [];

    <% @order.shipments.each do |shipment| %>
            shipments.push(<%== shipment.as_json(root: false, only: [:id, :tracking, :number, :state, :stock_location_id], include: [:inventory_units, :stock_location]).to_json %>);
    <% end %>
  <% end -%>
</div>

app/views/spree/admin/orders/_line_items.html.erb
<table class="line-items index" data-hook="line-items">
  <colgroup>
    <col style="width: 10%;" />
    <col style="width: 45%;" />
    <col style="width: 10%;" />
    <col style="width: 10%;" />
    <col style="width: 10%;" />
    <col style="width: 15%;" />
  </colgroup>

  <thead>
    <tr>
      <th colspan="2"><%= Spree::Product.human_attribute_name(:name) %></th>
      <th><%= Spree::LineItem.human_attribute_name(:price) %></th>
      <th><%= Spree::LineItem.human_attribute_name(:quantity) %></th>
      <th><%= Spree::LineItem.human_attribute_name(:total) %></th>
      <th class="orders-actions actions" data-hook="admin_order_form_line_items_header_actions">&nbsp;</th>
    </tr>
  </thead>

  <tbody>
    <%# Rendered by JS %>
  </tbody>
</table>

app/views/spree/admin/orders/_line_items_edit_form.html.erb
<div data-hook="admin_order_form_fields" class="js-order-cart-page" data-order-number="<%= @order.number %>">
  <% if @line_item.try(:errors).present? %>
      <%= render partial: 'spree/shared/error_messages', locals: { target: @line_item } %>
  <% end %>

  <%= render partial: "spree/admin/orders/line_items", locals: { order: order } %>

  <% if can?(:update, @order) && can?(:create, Spree::LineItem) %>
    <button class="js-add-line-item btn btn-primary" disabled><%= t('spree.add_line_item') %></button>
    <button class="js-empty-cart btn btn-primary" disabled><%= t('spree.empty_cart') %></button>
  <% end %>

  <%= render "spree/admin/orders/order_details", { order: order } %>
</div>

app/views/spree/admin/orders/_order_details.html.erb
<div class="js-order-line-item-adjustments <%= "hidden" if order.line_item_adjustments.eligible.none? %>">
  <%=
    render "spree/admin/orders/adjustments", {
      adjustments: order.line_item_adjustments,
      order: order,
      title: t('spree.line_item_adjustments')
    }
  %>
</div>
<div class="js-order-shipment-adjustments <%= "hidden" if order.shipment_adjustments.eligible.none? %>">
  <%=
    render "spree/admin/orders/adjustments", {
      adjustments: order.shipment_adjustments,
      order: order,
      title: t('spree.shipment_adjustments')
    }
  %>
</div>
<div class="js-order-adjustments <%= "hidden" if order.adjustments.eligible.none? %>">
  <%=
    render "spree/admin/orders/adjustments", {
      adjustments: order.adjustments,
      order: order,
      title: t('spree.order_adjustments')
    }
  %>
</div>

<fieldset class="no-border-bottom <%= "hidden" if order.line_items.none? %>" id="order-total" data-hook="order_details_total">
  <legend><%= t('spree.order_total') %></legend>
  <span class="order-total"><%= order.display_total %></span>
</fieldset>

app/views/spree/admin/orders/_risk_analysis.html.erb
<fieldset class="no-border-bottom" id="risk_analysis">
  <legend><%= "#{t('spree.risk_analysis')}: #{t('spree.not') unless @order.is_risky?} #{t('spree.risky')}" %></legend>
  <table>
    <thead>
      <th><%= t('spree.risk')%></th>
      <th><%= t('spree.status')%></th>
    </thead>
    <tbody id="risk-analysis" data-hook="order_details_adjustments"  class="with-border">
      <tr class="">
        <td><strong>
          <%= t('spree.failed_payment_attempts') %>:
        </strong></td>
        <td>
          <span class="pill pill-<%= @order.payments.failed.count > 0 ? 'warning' : 'complete' %>">
            <%= t(
              'spree.payments_failed_count',
              count: @order.payments.failed.count
            ) %>
          </span>
        </td>
      </tr>

      <tr>
        <td><strong><%= t('spree.avs_response') %>:</strong></td>
        <td>
          <span class="pill pill-<%= latest_payment.is_avs_risky? ? 'warning' : 'complete' %>">
            <% if latest_payment.is_avs_risky? %>
              <%= avs_response_code[latest_payment.avs_response] %>
            <% else %>
              <%= t('spree.success') %>
            <% end %>
          </span>
        </td>
      </tr>

      <tr>
        <td><strong><%= t('spree.cvv_response') %>:</strong></td>
        <td>
          <span class="pill pill-<%= latest_payment.is_cvv_risky? ? 'warning' : 'complete' %>">
            <% if latest_payment.is_cvv_risky? %>
              <%= cvv_response_code[latest_payment.cvv_response_code] %>
            <% else %>
              <%= t('spree.success') %>
            <% end %>
          </span>
        </td>
      </tr>
    </tbody>
  </table>
</fieldset>

app/views/spree/admin/orders/_shipment_manifest.html.erb
<% shipment_manifest.each do |item| %>
  <tr class="stock-item"
      data-item-quantity="<%= item.quantity %>"
      data-variant-id="<%= item.variant.id %>"
      >
    <td class="item-image align-center">
      <%= render 'spree/admin/shared/image',
        image: (item.variant.gallery.images.first || item.variant.product.gallery.images.first),
        size: :mini %>
    </td>
    <td class="item-name">
      <%= link_to item.variant.product.name, edit_admin_product_path(item.variant.product) %><br><%= "(" + variant_options(item.variant) + ")" unless item.variant.option_values.empty? %>
      <% if item.variant.sku.present? %>
        <strong><%= Spree::Variant.human_attribute_name(:sku) %>:</strong> <%= item.variant.sku %>
      <% end %>
    </td>
    <td class="item-price"><%= item.line_item.single_money.to_html %></td>
    <td class="item-qty-show">
        <% item.states.each do |state,count| %>
          <%= count %> x <%= t(state, scope: 'spree.inventory_states') %>
        <% end %>
    </td>
    <td class="item-total"><%= line_item_shipment_price(item.line_item, item.quantity) %></td>

    <td class="cart-item-delete actions" data-hook="cart_item_delete">
      <% if can? :update, item %>
        <%= button_tag '', class: 'split-item icon_link fa fa-arrows-h no-text with-tip', data: { action: 'edit', 'variant-id' => item.variant.id }, title: t('spree.actions.split'), type: :button %>
        <%= button_tag '', class: 'delete-item fa fa-trash no-text with-tip', data: { action: 'remove', 'variant-id' => item.variant.id }, title: t('spree.actions.delete'), type: :button %>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/spree/admin/orders/cart.html.erb
<% content_for :page_actions do %>
    <% if can?(:fire, @order) %>
      <li><%= event_links %></li>
    <% end %>
    <% if can?(:resend, @order) && @order.completed? %>
      <li><%= button_to t('spree.resend'), resend_admin_order_url(@order), method: :post %></li>
    <% end %>
<% end %>

<%= render partial: 'spree/admin/shared/order_tabs', locals: { current: 'Cart' } %>

<% admin_breadcrumb(t('spree.cart')) %>


<div data-hook="admin_order_edit_header">
  <%= render partial: 'spree/shared/error_messages', locals: { target: @order } %>
</div>

<% if @order.payments.exists? && @order.is_risky? %>
    <%= render 'spree/admin/orders/risk_analysis', latest_payment: @order.payments.reorder("created_at DESC").first %>
<% end %>

<div data-hook="admin_order_edit_form">
  <div id="order-form-wrapper">
    <%= render partial: 'line_items_edit_form', locals: { order: @order } %>
  </div>
</div>

app/views/spree/admin/orders/index.html.erb
<% admin_layout "full-width" %>

<% admin_breadcrumb(plural_resource_name(Spree::Order)) %>


<% content_for :page_actions do %>
  <li>
    <%= link_to t('spree.new_order'), new_admin_order_url, id: 'admin_new_order', class: 'btn btn-primary' %>
  </li>
<% end if can? :manage, Spree::Order %>

<% content_for :table_filter_title do %>
  <%= t('spree.filter') %>
<% end %>

<% content_for :table_filter do %>
  <div data-hook="admin_orders_index_search">
    <%= search_form_for [:admin, @search] do |f| %>
      <div class="row">
        <div class="field-block col-12 col-md-6 col-lg-4 col-xl-3">
          <div class="date-range-filter field">
            <%= label_tag :q_created_at_gt, t('spree.date_range') %>
            <div class="date-range-fields input-group">
              <%= f.text_field :created_at_gt, class: 'datepicker form-control datepicker-from', value: params[:q][:created_at_gt], placeholder: t('spree.start') %>

              <div class="input-group-prepend input-group-append">
                <span class="input-group-text range-divider">
                  <i class="fa fa-arrow-right"></i>
                </span>
              </div>

              <%= f.text_field :created_at_lt, class: 'datepicker form-control datepicker-to', value: params[:q][:created_at_lt], placeholder: t('spree.stop') %>
            </div>
          </div>

          <div class="field">
            <%= label_tag :q_state_eq, t('spree.status') %>
            <%= f.select :state_eq, Spree::Order.state_machines[:state].states.collect {|s| [t(s.name, scope: 'spree.order_state'), s.value]}, {include_blank: true}, class: 'custom-select fullwidth' %>
          </div>

          <div class="field">
            <%= label_tag nil, t('spree.promotion') %>
            <%= f.text_field :order_promotions_promotion_code_value_start, size: 25 %>
          </div>

          <div class="field">
            <%= label_tag nil, t('spree.shipment_number') %>
            <%= f.text_field :shipments_number_start %>
          </div>

          <div class="field">
            <%= label_tag :q_shipment_state, t('spree.shipment_state') %>
            <%= f.select :shipment_state_eq, %i[backorder canceled partial pending ready shipped].map { |state| [t("spree.shipment_states.#{state}"), state] }, { include_blank: true }, { class: "custom-select fullwidth" } %>
          </div>
        </div>

        <div class="col-12 col-md-6 col-lg-4 col-xl-6">
          <div class="row">
            <div class="col-12 col-xl-6">
              <div class="field">
                <%= label_tag :q_number_start, t('spree.order_number', number: '') %>
                <%= f.text_field :number_start %>
              </div>

              <div class="field">
                <%= label_tag :q_email_start, t('spree.email') %>
                <%= f.text_field :email_start %>
              </div>
            </div>

            <div class="col-12 col-xl-6">
              <div class="field">
                <%= label_tag :q_bill_address_name_start, t('spree.name_contains') %>
                <%= f.text_field :bill_address_name_start, size: 25 %>
              </div>
            </div>

            <div class="col-12 col-xl-6">
              <div class="field" data-hook="sku-select">
                <%= label_tag :q_line_items_variant_id_in, t('spree.variant') %>
                <%= f.text_field :line_items_variant_id_in, class: "variant_autocomplete fullwidth" %>
              </div>
            </div>
          </div>
        </div>

        <div class="col-12 col-md-6 col-lg-4 col-xl-3">
          <% if Spree::Store.count > 1 %>
            <div class="field">
              <%= label_tag :q_store_id_eq, t('spree.store') %>
              <%= f.select :store_id_eq, Spree::Store.all.map { |s| [s.name, s.id] }, { include_blank: true }, { class: "custom-select fullwidth" } %>
            </div>
          <% end %>

          <div class="field checkbox">
            <label>
              <%= f.check_box :completed_at_not_null, {checked: @show_only_completed}, '1', '0' %>
              <%= t('spree.show_only_complete_orders') %>
            </label>
          </div>
        </div>

      </div>

      <div class="clearfix"></div>

      <div class="actions filter-actions">
        <div data-hook="admin_orders_index_search_buttons">
          <%= button_tag t('spree.filter_results'), class: 'btn btn-primary' %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<%= paginate @orders, theme: "solidus_admin" %>

<% if @orders.any? %>
  <table class="index" id="listing_orders" data-hook>
    <colgroup>
       <col style="width: 13%;">
       <col style="width: 10%;">
       <col style="width: 10%;">
       <col style="width: 12%;">
       <% if Spree::Order.checkout_step_names.include?(:delivery) %>
         <col style="width: 12%;">
       <% end %>
       <col style="width: 25%;">
       <col style="width: 10%;">
       <col style="width: 8%;">
    </colgroup>
    <thead>
      <tr data-hook="admin_orders_index_headers">
        <% if @show_only_completed %>
          <th><%= sort_link @search, :completed_at %></th>
        <% else %>
          <th><%= sort_link @search, :created_at %></th>
        <% end %>
        <th><%= sort_link @search, :number %></th>
        <th><%= sort_link @search, :state %></th>
        <th><%= sort_link @search, :payment_state %></th>
        <% if Spree::Order.checkout_step_names.include?(:delivery) %>
          <th><%= sort_link @search, :shipment_state %></th>
        <% end %>
        <th><%= sort_link @search, :email %></th>
        <th class="align-right"><%= sort_link @search, :total %></th>
        <th data-hook="admin_orders_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
    <% @orders.each do |order| %>
      <tr data-hook="admin_orders_index_rows">
        <td><%= l (@show_only_completed ? order.completed_at : order.created_at).to_date %></td>
        <td><%= link_to order.number, edit_admin_order_path(order) %></td>
        <td>
          <span class="pill pill-<%= order.state %>">
            <%= t(order.state, scope: 'spree.order_state') %>
          </span>
        </td>
        <td>
          <% if order.payment_state  %>
            <span class="pill pill-<%= order.payment_state %>">
              <%= t(order.payment_state, scope: 'spree.payment_states') %>
            </span>
          <% end %>
        </td>
        <% if Spree::Order.checkout_step_names.include?(:delivery) %>
          <td>
            <% if order.shipment_state %>
              <span class="pill pill-<%= order.shipment_state %>">
                <%= t(order.shipment_state, scope: 'spree.shipment_states') %>
              </span>
            <% end %>
          </td>
        <% end %>
        <td>
          <% if order.user %>
            <%= link_to order.email, edit_admin_user_path(order.user) %>
          <% else %>
            <%= order.email %>
          <% end %>
          <%= link_to_with_icon('email', t('spree.actions.send_email'), "mailto:#{order.email}", no_text: true) %>
        </td>
        <td class="align-right"><%= order.display_total.to_html %></td>
        <td class='actions align-center' data-hook="admin_orders_index_row_actions">
          <%= link_to_edit_url edit_admin_order_path(order), title: "admin_edit_#{dom_id(order)}", no_text: true %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <div class="no-objects-found">
    <% if can? :manage, Spree::Order %>
      <%= render 'spree/admin/shared/no_objects_found',
                   resource: Spree::Order,
                   new_resource_url: spree.new_admin_order_path %>
    <% end %>
  </div>
<% end %>

<%= paginate @orders, theme: "solidus_admin" %>